### ISSUE TITLE
Using `class` in a Vue template causes parsing error

### ISSUE THREAD

**Issue by onlyjsmith** [dyatko/arkit#145]
Bug description

Including `class` on a template element (even commented-out) results in a parsing error, and file to be missing from output SVG.

`[2019-08-29 06:10:00.902 +0000] ERROR: Error parsing <...>/src/views/Test.vue`

**To Reproduce**
1. Operating system: _macOS 10.14.6_
2. Arkit version and CLI arguments: _v1.6.2_
- `arkit -e "node_modules" src/views`

3. Arkit config, if any was used: _none_

4. Source code example, if it's possible: 

`src/views/Test.vue`

**FAIL**
```vue
<template>
  <div class='thing'></div>
</template>

<script>
</script>
```

**PASS**
```vue
<template>
  <div></div>
</template>

<script>
</script>
```

**Comment by danivalls** [comment]
Any updates on this?

**Comment by clorichel** [comment]
Exact same scenario here: can't get any `.vue` file to be parsed if this file's template contains a `class`. An `App.vue` that is parsed without a problem:

```
<template>
  <div></div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class App extends Vue {}
</script>
```

An `App.vue` that can't be parsed (notice the only addition is `class="whatever"` on the template div):

```
<template>
  <div class="whatever"></div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class App extends Vue {}
</script>
```

Here is the `LEVEL=info` error detail:

```
[2020-04-17 09:43:20.696 +0000] WARN : Unexpected scenario where a(n) OpenBraceToken was not found.
    Error: Unexpected scenario where a(n) OpenBraceToken was not found.
        at getTokenEnd (/myproject/node_modules/ts-morph/dist/ts-morph.js:1109:23)
        at Function.getContainerBodyPos (/myproject/node_modules/ts-morph/dist/ts-morph.js:1101:20)
        at isStatementMemberOrPropertyHoldingSyntaxList (/myproject/node_modules/ts-morph/dist/ts-morph.js:1325:38)
        at Function.getCompilerChildren (/myproject/node_modules/ts-morph/dist/ts-morph.js:1309:13)
        at SyntaxList._getCompilerChildren (/myproject/node_modules/ts-morph/dist/ts-morph.js:3773:31)
        at SyntaxList._getCompilerChildrenFast (/myproject/node_modules/ts-morph/dist/ts-morph.js:3779:58)
        at SyntaxList._getChildrenInCacheIterator (/myproject/node_modules/ts-morph/dist/ts-morph.js:3111:31)
        at _getChildrenInCacheIterator.next (<anonymous>)
        at CompilerFactory.initializeNode (/myproject/node_modules/ts-morph/dist/ts-morph.js:18282:28)
        at /myproject/node_modules/ts-morph/dist/ts-morph.js:18249:28
[2020-04-17 09:43:20.718 +0000] ERROR: Error parsing /myproject/src/App.vue
```

@dyatko would you need help on this one, say a reproduction repo, or maybe I might try and figure out a failing test case? Please feel free to share any pointer anyways 🤗

Looking forward to get my WOW diagram ❤️

**Comment by tianjidiaobao** [comment]
Any updates on this?

**Comment by badihi** [comment]
On this update any?!

**Comment by badihi** [comment]
I could somehow workaround this problem, by some modifications:

https://github.com/badihi/arkit/commit/335e27aea10a53eac07ae760d3c350d553fa3404

I'm not sure that this will be eligible to be merged, but at least can be used as a workaround.
