### ISSUE TITLE
Not found tsconfig.json

### ISSUE THREAD

**Issue by yarkovaleksei** [dyatko/arkit#32]
Does not work. Cannot find the file `/home/user/git/tsconfig.json`, but it has never been there.

**To Reproduce**
1. Linux Ubuntu 18.04
2. Arkit version 1.3.17
3. Command `npx arkit ./src/ -o arkit.svg`

Result of performance:

```
npx: установлен 268 в 3.057s
Running against /home/user/git/toster-extension/src with the following config:
{
  "components": [
    {
      "type": "Dependency",
      "patterns": [
        "node_modules/*"
      ]
    },
    {
      "type": "Component",
      "patterns": [
        "**/*.ts",
        "**/*.js",
        "**/*.jsx",
        "**/*.tsx"
      ]
    }
  ],
  "excludePatterns": [
    "../test",
    "../tests",
    "../dist",
    "../coverage",
    "../**/*.test.*",
    "../**/*.spec.*",
    "../**/*.min.*"
  ],
  "output": [
    {
      "path": [
        "../arkit.svg"
      ],
      "groups": [
        {
          "first": true,
          "components": [
            "Component"
          ]
        },
        {
          "type": "Dependencies",
          "components": [
            "Dependency"
          ]
        }
      ]
    }
  ]
}
File not found: /home/user/git/tsconfig.json
```

**Comment by yarkovaleksei** [comment]
Checked on [this](https://github.com/yarkovaleksei/toster-extension) project

**Comment by dyatko** [comment]
@yarkovaleksei please re-try with arkit@1.4.0, which generated the following graph for me:

<img src="https://arkit.herokuapp.com/svg/UDgTM4sFv2OGlVjNe3tr7ZmplSb4McapscYb77F9tA88OPjsayRW0EwUIPJ_7ZviDpRWflVMfbuze2Yg7lrLAYJKqD6Ya3MY67Je3Um_Vte25zAeOq7nGG75WI3jKO6625mhmfb6dmZhaK0Tw3ZZzL7m3WCb1knPv14r_49O2mw8Ij_2U8Cbxi4FJzwWGEna1d_o1njyG0DLltAcVaDwYbTqv1sA0tud_s2m_-HJye4rtxXWM80VVQUUWFspFmyIWb--SSe5g2YgJslJwv7K9uQb14yFpy-UjTTWrE9NeYZ-XPAMTPWfOEBc1scGk4OIWtyB02ek6YmMXCL_FjW46R6MPi9htlMScLbZyBq15plKzm_d0N_KlmPrv4AMTfkKI9KQVoIimMyVY-joFdofNaAOh0NfrPV7wkK3G1B04G5d17I8OgVTAptMscCn3WloIWUerDiWwjqHcG7e1ehTl4iPMLVDcKvaRNEEywUFQVXGKLpsg2KCcIHsFCx36U7L2AtHBjcjmA63HHymKeF0ZcNyi5xZRxdj9n_LUu_bmbr2EsPPMiehH1_2O1r9WwzdK4wdylU0fLc-z3TdiDvfJESpOyUzfjaLQlEe3V0cRuDh8hLzWt62tEJgk5uUOGeBWsEjNZIlJm6VWK4F1YqimIamHGet9P5IpvvW747GWJRv9AU3sKDP3KejqyvIJNRex0cMCweHgubU469DQIzvQcqp56eeTD3a2fNgHrVzo-RSNpf63_eA7KWRf1qbbNpKjSIvc2-elugT7G_lfHtsCjmwNBERahC-4SfHcD-cgqXTMt5vq9NTt-9iWSOotLFUkn1pJZ5YOqbR3iRhsGgpBcRE34VpLCbY53OkQySnF1ueNWvq9PTOE4_tsxTEjy3PfwyOekm5FXDyyGCssU1eyqgRu9GEVUgm9JhZKk4tLLRum8Kv2j6L4hD6No5_1WE41WWT41eW785XpiaZlvI8qha0k093M7bjEoEnHaADlEx1LXZ2e2qtSMQcTO8Xcsj7dDR03DErn2Gu5HUwmO-UxcDXlw1UtqbvmS9UpTLrNnGtWuKEQ-_cwkfFLMvdux5kqCl1U3QlCEjijj6BzcNhw3BFvO4Tr6Lp_Xu4BLjgLk9DgNLDUSBl5KT2xtoeEg9iblYRrXWuOQ33k0G9GZtCTs1OtG3phNER7uXfuM6E6piSxUiyrn6cqcr81x9SjjHfjEFDG76aqLw4FbxPSqqiofhRlgWhwU9O3GQE66WmhjfEnrcanHKeonUGb6IXNWBb7sgITZ_l_tpnjKueaHBiK-ga7E9bCuMEfsLAKLcVcD89L5QuLLzUPS3dEfc9jpatJUBMwIlGfIMoWuZY2oVP4ffP1DyxSQO8_5w-gFAxZomf-kwZsTHwzr5jYBpxYE8IxpwEcwekcowke7AzD-H4bd-EMCWdon48zx5jwe9yginEdyjteudUmvDibBaSDzhTgaIvUkaf_ynI5AspEMLdmp5LOZPSjih9XbkwT6muHSl41lvMIOYxJgysPxtgXvN1lWTNO_ufBYsJCFPVWXvFE1nzEmQpXCRaH9FEYvQtUDEE2fsO1d9wp7_J1RSYyWVL4h-Xt6u0Lw_cy2KPBcR-kszyJOuHcYNyV04YEcTfyezyQPbEOZNiP5IyIyGJCgCZ91mpgl-6vrQbJxYvBOUHoIltyIoC2kYOjhw-2jQlDOqEKi3_IoRkiywpyO-7rSilIu9kulr0RVUnUDI7AO6NUNeTzcvIkh_5kRTxMTId-AepS-Ze_meMCkS0?raw" />

**Comment by yarkovaleksei** [comment]
It worked only by going to the `src` folder and running the script there.

**Comment by dyatko** [comment]
@yarkovaleksei strange, I run from the project root directory.
Could you please provide `LEVEL=trace npx arkit` output from it?

**Comment by yarkovaleksei** [comment]
```
user@ubuntu:[~/git/toster-extension](master)$ arkit -v
1.4.0
user@ubuntu:[~/git/toster-extension](master)$ LEVEL=trace arkit src/ -o arkit.svg
[2019-03-15 13:03:40.152 +0000] INFO : Options
[2019-03-15 13:03:40.154 +0000] INFO : 
    _: "src/"
    o: [
      "arkit.svg"
    ]
    output: [
      "../arkit.svg"
    ]
    directory: "/home/user/git/toster-extension/src"
    d: "src/"
    exclude: [
      "../test",
      "../tests",
      "../dist",
      "../coverage",
      "../**/*.test.*",
      "../**/*.spec.*",
      "../**/*.min.*"
    ]
    e: [
      "test",
      "tests",
      "dist",
      "coverage",
      "**/*.test.*",
      "**/*.spec.*",
      "**/*.min.*"
    ]
    $0: "arkit"
[2019-03-15 13:03:40.154 +0000] TRACE: Error: Cannot find module '/home/user/git/toster-extension/src/arkit'
[2019-03-15 13:03:40.154 +0000] TRACE: Error: Cannot find module '/home/user/git/toster-extension/src/package'
Running against /home/user/git/toster-extension/src with the following config:
{
  "components": [
    {
      "type": "Dependency",
      "patterns": [
        "node_modules/*"
      ]
    },
    {
      "type": "Component",
      "patterns": [
        "**/*.ts",
        "**/*.js",
        "**/*.jsx",
        "**/*.tsx"
      ]
    },
    {
      "type": "Vue",
      "format": "full",
      "patterns": [
        "**/*.vue"
      ]
    }
  ],
  "excludePatterns": [
    "../test",
    "../tests",
    "../dist",
    "../coverage",
    "../**/*.test.*",
    "../**/*.spec.*",
    "../**/*.min.*"
  ],
  "output": [
    {
      "path": [
        "../arkit.svg"
      ],
      "groups": [
        {
          "first": true,
          "components": [
            "Component",
            "Vue"
          ]
        },
        {
          "type": "Dependencies",
          "components": [
            "Dependency"
          ]
        }
      ]
    }
  ]
}
[2019-03-15 13:03:40.158 +0000] DEBUG: Found TypeScript config ../tsconfig.json
[2019-03-15 13:03:40.158 +0000] DEBUG: Registering ts-config paths...
[2019-03-15 13:03:40.158 +0000] DEBUG: 
    @/*: [
      "src/*"
    ]
    assets/*: [
      "assets/*"
    ]
/home/user/.nvm/versions/node/v10.0.0/lib/node_modules/arkit/node_modules/ts-morph/dist/fileSystem/DefaultFileSystemHost.js:59
            throw this.getFileNotFoundErrorIfNecessary(err, filePath);
            ^

Error: File not found: /home/user/git/tsconfig.json
    at FileNotFoundError.BaseError [as constructor] (/home/user/.nvm/versions/node/v10.0.0/lib/node_modules/arkit/node_modules/ts-morph/dist/errors/classes/BaseError.js:8:28)
    at FileNotFoundError.PathNotFoundError [as constructor] (/home/user/.nvm/versions/node/v10.0.0/lib/node_modules/arkit/node_modules/ts-morph/dist/errors/classes/PathNotFoundError.js:11:28)
    at new FileNotFoundError (/home/user/.nvm/versions/node/v10.0.0/lib/node_modules/arkit/node_modules/ts-morph/dist/errors/classes/FileNotFoundError.js:9:23)
    at DefaultFileSystemHost.getFileNotFoundErrorIfNecessary (/home/user/.nvm/versions/node/v10.0.0/lib/node_modules/arkit/node_modules/ts-morph/dist/fileSystem/DefaultFileSystemHost.js:184:58)
    at DefaultFileSystemHost.readFileSync (/home/user/.nvm/versions/node/v10.0.0/lib/node_modules/arkit/node_modules/ts-morph/dist/fileSystem/DefaultFileSystemHost.js:59:24)
    at FileSystemWrapper.readFileSync (/home/user/.nvm/versions/node/v10.0.0/lib/node_modules/arkit/node_modules/ts-morph/dist/fileSystem/FileSystemWrapper.js:733:32)
    at TsConfigResolver.getTsConfigFileJson (/home/user/.nvm/versions/node/v10.0.0/lib/node_modules/arkit/node_modules/ts-morph/dist/utils/tsconfig/TsConfigResolver.js:105:36)
    at TsConfigResolver.decorator [as getTsConfigFileJson] (/home/user/.nvm/versions/node/v10.0.0/lib/node_modules/arkit/node_modules/ts-morph/dist/utils/decorators/Memoize.js:27:46)
    at TsConfigResolver.parseJsonConfigFileContent (/home/user/.nvm/versions/node/v10.0.0/lib/node_modules/arkit/node_modules/ts-morph/dist/utils/tsconfig/TsConfigResolver.js:100:70)
    at TsConfigResolver.decorator [as parseJsonConfigFileContent] (/home/user/.nvm/versions/node/v10.0.0/lib/node_modules/arkit/node_modules/ts-morph/dist/utils/decorators/Memoize.js:27:46)
```

**Comment by dyatko** [comment]
You might have TS_NODE_PROJECT env variable defined, from what I see at this line https://github.com/dividab/tsconfig-paths/blob/6da68cbec7f11aa84ec7aeb14732d9edcdb82b68/src/tsconfig-loader.ts#L37

Could you check it running `echo $TS_NODE_PROJECT`?

**Comment by dyatko** [comment]
@yarkovaleksei or better try arkit@1.4.1 that should reveal the correct tsconfig path running `LEVEL=trace npx arkit`

**Comment by yarkovaleksei** [comment]
> Could you check it running echo $TS_NODE_PROJECT?

Nothing

**Comment by yarkovaleksei** [comment]
Yes, with version 1.4.1 everything works correctly

**Comment by dyatko** [comment]
Great, thank for reporting!
